### ISSUE TITLE
Additional bad configurations

### ISSUE THREAD

**Issue by lgarron** [lgarron/badssl.com#1]
## Certificate Issues

- [ ] SHA-1 expiring in 2017 (#16)
- [ ] OCSP / CT? (#17)
  - Maybe must-staple without stapling?
- [ ] `weak-rsa.badssl.com` (idea from @noncombatant) (#18)
- [x] `missing-intermediary.badssl.com` or `incomplete-chain.badssl.com` (idea from @noncombatant)
- [x] `hostname-mismatch.badssl.com` or `wrong.host.badssl.com` (idea from @saschaf)
  - Perhaps make `wrong-host.badssl.com` work instead, to avoid confusion about which ones are hyphenated?

## Cipher Suites / Protocol

- [x] CBC
- [ ] SSLv3 (#20)
- [ ] TLSv1 (#21)
- [ ] Other SSL/TLS versions?
- [ ] Mozilla's [modern/intermediate/old configs](https://mozilla.github.io/server-side-tls/ssl-config-generator/). [#22]
  - [ ] Modern one at [`not.badssl.com`](https://not.badssl.com)? :-P
- [ ] `no-pfs.badssl.com` (idea from @noncombatant) (#23)
- [ ] `export.badssl.com` (export-grade ciphersuites; idea from @noncombatant) (#24)
- [x] Weak EDH key (see [`demo.cmrg.net`](https://demo.cmrg.net/)). (44df428186b432583cee701df388184726f54a4b and aea4d8e05fadd8edc42db127e9cae1ffdaec9924)

## Headers
- [x] HSTS
  - [x] preloaded-hsts.badssl.com
- [ ] HPKP (#15)

## Content

- [x] Mixed Content
- [ ] Mixed Scripts (#33)
- `mixed-____.badssl.com`? (image, audio, video, XHR, Flash, [etc.](https://www.bennish.net/mixed-content.html))
- [ ] Migrate `mixed-content-test.appspot.com`? (#32)

## Misc

- [ ] oe.badssl.com (opportunistic encryption; idea from @noncombatant) (#25)
- [x] http.badssl.com (redirect to HTTP)

**Comment by lgarron** [comment]
Additional ideas from @noncombatant:

- [ ] no-pfs.badssl.com
- [ ] weak-rsa.badssl.com
- [ ] missing-intermediary.badssl.com
- [ ] export.badssl.com
- [ ] oe.badssl.com

And from Will:

- [ ] mixed-script-content.badssl.com (also see [mixed-content-test.appspot.com](https://mixed-content-test.appspot.com/)).

**Comment by lgarron** [comment]
- [ ] preloaded-hsts.badssl.com

**Comment by lgarron** [comment]
- [ ] OCSP/CT Issues? (Maybe `must-staple` without stapling.)

**Comment by marumari** [comment]
Could probably also do:
- Invalid fingerprint
- Missing required client certificate
- Incorrect key usage (ie, lacks keyEncipherment or serverAuth)
- Presumably you mean a revoked certificate, with OCSP / CT?  If not, a certificate for revoked.badssl.com that has been revoked would be a nice demo.

Also, in addition to something like not.badssl.com (which is hilarious), it'd be neat to have a bleedingedge.badssl.com (ie, TLS 1.2, ECDHE, ECDSA, AEADs only).

**Comment by hotaru2k3** [comment]
weak DH would be great... but you'd probably need separate ones for 512-bit and 1024-bit (and maybe 768 as well).

**Comment by marumari** [comment]
Weak DH should be really easy to do, but I'm a bit worried about having too large of a pull request for lgarron to deal with. O_o

I think 768 is probably overkill -- I imagine most clients either treat it like 512 or treat it like 1024.  Shall we call it broken-diffie-hellman.badssl.com and weak-diffie-hellman.badssl.com?

**Comment by lgarron** [comment]
> I think 768 is probably overkill -- I imagine most clients either treat it like 512 or treat it like 1024. Shall we call it broken-diffie-hellman.badssl.com and weak-diffie-hellman.badssl.com?

I ended up naming the ones we have `dh480` and `dh512` because:
- it's shorter
- it's less subjective (the Chrome error for [`dh480.badssl.com`](https://dh480.badssl.com/)) is actually `ERR_SSL_WEAK_SERVER_EPHEMERAL_DH_KEY` instead of "broken")
- even the OpenSSL source [uses this abbreviation convention](https://github.com/openssl/openssl/blob/master/apps/dh512.pem).

However, this makes it easy to include `dh768`. If there are *any* clients that behave differently with `dh768`, I think it would it be worth including.

**Comment by lgarron** [comment]
I've split everything from this issue into individual issues. The first post has been updated with links to the issues.

**Comment by marumari** [comment]
IIRC, Safari was the only browser to even have the slightest frowny at dh512; I imagine its behavior changes at dh1024, but I will check when I get a chance.

**Comment by lgarron** [comment]
Safari don't give me no frowney. :-(
![screen shot 2015-05-15 at 13 07 03](https://cloud.githubusercontent.com/assets/248078/7660938/672b08da-fb03-11e4-891b-a51ab41f9196.png)

Anyhow, it seems there might be more conversation to be had on DH, so I've made issue #35.

**Comment by marumari** [comment]
Weird, it looks like a regression in 10.10.  I'm still on 10.9 over here:

http://i.imgur.com/hvAO3Bn.png

**Comment by lgarron** [comment]
The red lock on your screenshot is probably the favicon. :-P
(I don't see anything else frowny, but then I'm zooming and panning on
mobile.)

**Comment by marumari** [comment]
That's the *favicon*?  How embarrassing!  I thought they all hid the favicon over https for this very reason.  Looks like from your screenshot that they changed that behavior in 10.10.

Okay, so then no browser manufacturers alert for 512-bit DH keys.  The only people that seem to actually be on top of it are the Qualys folks:

https://www.ssllabs.com/ssltest/analyze.html?d=dh512.badssl.com

... who rightly give dh512.badssl.com a failing grade.

**Comment by rugk** [comment]
> That's the favicon? How embarrassing! I thought they all hid the favicon over https for this very reason. 

No. No browser hides the favicon.
FYI that's even a technology used by the attack [ssl stripping](http://www.thoughtcrime.org/software/sslstrip/).

**Comment by lgarron** [comment]
> No. No browser hides the favicon.

While SSL stripping and favicon manipulation are definitely worrisome tricks, I hope you'll concede that Safari *does* hide the favicon while you're not editing the URL bar, as in the screenshot above. ;-)

**Comment by rugk** [comment]
Okay, okay. :smiley: 
But I doubt that it shows the favicon on http:// connections...
